project:
  type: website

website:
  title: "Ferran Garcia"
  search: false
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Footer here!"
  navbar:
    right:
      - text: About
        menu:
          - text: English
            href: about-en.qmd
          - text: Català
            href: about-ca.qmd
          - text: Español
            href: about-es.qmd
format:
  html:
    theme: [cosmo, styles.scss]

